// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CatchCourse(arg1:number,arg2:string,arg3:string,arg4:string,arg5:string):Promise<void>;

export function Dialog(arg1:string,arg2:string):Promise<string>;

export function InstallBrowser():Promise<void>;

export function WatchCourse(arg1:number,arg2:string,arg3:string,arg4:string,arg5:string):Promise<void>;
