// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CatchCourseMaj(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['CatchCourseMaj'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function CatchCoursePub(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['CatchCoursePub'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function Dialog(arg1, arg2) {
  return window['go']['main']['App']['Dialog'](arg1, arg2);
}

export function InstallBrowser() {
  return window['go']['main']['App']['InstallBrowser']();
}

export function WatchCourseMaj(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['WatchCourseMaj'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function WatchCourseMajSync(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['WatchCourseMajSync'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function WatchCoursePub(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['WatchCoursePub'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function WatchCoursePubSync(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['WatchCoursePubSync'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}
