// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Dialog(arg1:string,arg2:string):Promise<string>;

export function GetTimetable(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function InstallBrowser():Promise<void>;
