// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Dialog(arg1, arg2) {
  return window['go']['main']['App']['Dialog'](arg1, arg2);
}

export function GetTimetable(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetTimetable'](arg1, arg2, arg3);
}

export function InstallBrowser() {
  return window['go']['main']['App']['InstallBrowser']();
}
