// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CatchCourse(arg1, arg2, arg3) {
  return window['go']['main']['App']['CatchCourse'](arg1, arg2, arg3);
}

export function Dialog(arg1, arg2) {
  return window['go']['main']['App']['Dialog'](arg1, arg2);
}

export function InstallBrowser() {
  return window['go']['main']['App']['InstallBrowser']();
}

export function WatchCourse(arg1, arg2, arg3) {
  return window['go']['main']['App']['WatchCourse'](arg1, arg2, arg3);
}
